site_name: Curator
theme:
  name: material
  features:
    - content.tabs.link
markdown_extensions:  
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 